-- 1. Create account_type type
-- We have found the difference in either of Type or SubType or Collation,
-- so we need to drop the existing type first and re-create it.
DROP TYPE public."Create_Type" CASCADE;
CREATE TYPE public."Create_Type" AS ENUM ('Client', 'Employee', 'Admin');
ALTER TYPE public."Create_Type" OWNER TO cse340_user;
-- 1. Create account_type type
-- 2. Create classification table
CREATE TABLE IF NOT EXISTS public.classification (
  classification_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  classification_name character varying NOT NULL,
  CONSTRAINT classification_pkey PRIMARY KEY (classification_id),
  CONSTRAINT classification_name_unique UNIQUE (classification_name)
);
-- 3. Create inventory table
CREATE TABLE IF NOT EXISTS public.inventory (
  inv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  inv_make character varying NOT NULL,
  inv_model character varying NOT NULL,
  inv_year character(4) NOT NULL,
  inv_description text NOT NULL,
  inv_image character varying NOT NULL,
  inv_thumbnail character varying NOT NULL,
  inv_price numeric(9, 2) NOT NULL,
  inv_miles integer NOT NULL,
  inv_color character varying NOT NULL,
  classification_id integer NOT NULL,
  CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)
);
-- 4. Create account table
CREATE TABLE IF NOT EXISTS public.account (
  account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  account_firstname character varying NOT NULL,
  account_lastname character varying NOT NULL,
  account_email character varying NOT NULL,
  account_password character varying NOT NULL,
  account_type account_type NOT NULL DEFAULT 'Client'::account_type,
  CONSTRAINT account_pkey PRIMARY KEY (account_id)
);
-- 5. Add foreign key relationship
ALTER TABLE public.inventory
ADD CONSTRAINT fk_classification FOREIGN KEY (classification_id) REFERENCES public.classification (classification_id) ON DELETE CASCADE;
-- 6. Insert classification data
INSERT INTO public.classification (classification_name)
VALUES ('Custom'),
  ('Sedan'),
  ('SUV'),
  ('Truck'),
  ('Sports');
-- 7. Insert inventory data
INSERT INTO public.inventory (
    inv_make,
    inv_model,
    inv_year,
    inv_description,
    inv_image,
    inv_thumbnail,
    inv_price,
    inv_miles,
    inv_color,
    classification_id
  )
VALUES (
    'Jeep',
    'Wrangler',
    '2018',
    'The Jeep Wrangler is small and compact with enough power to get you where you want to go. It is great for everyday driving as well as off-roading whether that be on the rocks or in the mud!',
    '/images/jeep-wrangler.jpg',
    '/images/jeep-wrangler-tn.jpg',
    28045.00,
    51236,
    'Orange',
    3
  ),
  (
    'Ford',
    'Model T',
    '1921',
    'The Ford Model T can be a bit tricky to drive. It was the first car to be put into production. You have to hand crank it to get it started. It has a top speed of 45 mph. It has a 4-cylinder engine.',
    '/images/ford-modelt.jpg',
    '/images/ford-modelt-tn.jpg',
    30000.00,
    20000,
    'Black',
    1
  ),
  (
    'Lamborghini',
    'Adventador',
    '2016',
    'This V-12 engine packs a punch in this sporty car. Make sure you wear your seatbelt and obey all traffic laws.',
    '/images/lambo-Adve.jpg',
    '/images/lambo-Adve-tn.jpg',
    417650.00,
    71003,
    'Blue',
    5
  ),
  (
    'Monster',
    'Truck',
    '1995',
    'Most trucks are for working, this one is for fun. This beast comes with 60 inch tires giving you the traction needed to jump and roll in the mud.',
    '/images/monster.jpg',
    '/images/monster-tn.jpg',
    150000.00,
    3500,
    'Purple',
    4
  ),
  (
    'Mechanic',
    'Special',
    '1964',
    'Not sure where this car has been, but you can be it will work when you get it home. This is a project car that would be perfect for someone with vision for restoration.',
    '/images/ms.jpg',
    '/images/ms-tn.jpg',
    750.00,
    120000,
    'Rust',
    1
  ),
  (
    'Batmobile',
    'Custom',
    '2021',
    'Ever want to be a superhero? Now you can with the batmobile. This car allows you to switch to bike mode allowing you to easily maneuver through traffic during your chase.',
    '/images/bat.jpg',
    '/images/bat-tn.jpg',
    65000.00,
    15,
    'Black',
    1
  ),
  (
    'Mystery',
    'Machine',
    '1999',
    'Scooby and the gang would be lost in this Mystery Machine. This van helps you solve all those hard to solve mysteries.',
    '/images/mystery.jpg',
    '/images/mystery-tn.jpg',
    10000.00,
    128564,
    'Green',
    1
  ),
  (
    'Spartan',
    'Fire Truck',
    '2012',
    'Emergencies happen often. Be prepared with this Spartan fire truck. Comes complete with 1000 ft. of hose and all the tools needed for any firefighting emergency.',
    '/images/fire-truck.jpg',
    '/images/fire-truck-tn.jpg',
    50000.00,
    38522,
    'Red',
    4
  ),
  (
    'Ford',
    'Crown Victoria',
    '2013',
    'After the police force updated their fleet these cars are now available to the public! These cars come equipped with the siren which is convenient for college students running late to class.',
    '/images/cr-vic.jpg',
    '/images/cr-vic-tn.jpg',
    10000.00,
    108247,
    'White',
    2
  );
-- 8. Task 1 Query 4 - Modify GM Hummer description
UPDATE public.inventory
SET inv_description = REPLACE(
    inv_description,
    'small interiors',
    'a huge interior'
  )
WHERE inv_make = 'GM'
  AND inv_model = 'Hummer';
-- 9. Task 1 Query 6 - Update image paths
UPDATE public.inventory
SET inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
  inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/');